const professions = [
  { title: "Teacher", pay: 5, joy: 7, stress: 3, increasedRisk: 0 },
  { title: "Lawyer", pay: 10, joy: 5, stress: 6, increasedRisk: 0.00001 },
  { title: "Cleaner", pay: 2, joy: 1, stress: 3, increasedRisk: 0 },
  { title: "Judge", pay: 20, joy: 5, stress: 5, increasedRisk: 0.00001 },
  { title: "Mayor", pay: 8, joy: 6, stress: 7, increasedRisk: 0.00001 },
  { title: "President", pay: 100, joy: 9, stress: 10, increasedRisk: 0.0001 },
  { title: "PE Teacher", pay: 4, joy: 5, stress: 2, increasedRisk: 0 },
  { title: "Secretary", pay: 5, joy: 5, stress: 5, increasedRisk: 0 },
  { title: "L33T Programmer", pay: 550, joy: 10, stress: 8, increasedRisk: 0 }, // !
  { title: "Programmer", pay: 200, joy: 8, stress: 10, increasedRisk: 0 },
  { title: "Tester", pay: 5, joy: 4, stress: 1, increasedRisk: 0 },
  {
    title: "Kinder-garden teacher",
    pay: 5,
    joy: 8,
    stress: 5,
    increasedRisk: 0,
  },
  { title: "ER Nurse", pay: 5, joy: 7, stress: 10, increasedRisk: 0.00004 },
  {
    title: "Low end Cashier",
    pay: 2,
    joy: 1,
    stress: 2,
    increasedRisk: 0.00003,
  },
  {
    title: "Mid-end Cashier",
    pay: 3,
    joy: 3,
    stress: 3,
    increasedRisk: 0.0002,
  },
  {
    title: "High-end Cashier",
    pay: 5,
    joy: 5,
    stress: 4,
    increasedRisk: 0,
  },
  {
    title: "Middle management",
    pay: 15,
    joy: 5,
    stress: 6,
    increasedRisk: 0.00002,
  },
  { title: "CEO", pay: 250, joy: 7, stress: 10, increasedRisk: 0.00001 },
  { title: "CFO", pay: 150, joy: 7, stress: 8, increasedRisk: 0.00001 },
  { title: "Accountant", pay: 9, joy: 5, stress: 4, increasedRisk: 0 },
  { title: "Police", pay: 7, joy: 6, stress: 8, increasedRisk: 0.0001 },
];
